---

- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the required packages for ntp
  package: name={{ item }} state=latest
  with_items: ntp_pkg

- name: Add ntp configuration file
  sudo: yes
  template: src=ntp.conf.j2  dest=/etc/ntp.conf
  register: ntp_setup

- name: Enable ntp service
  sudo: yes
  service:
    name={{ ntp_service }}
    state=running
    enabled=yes

- name: Restart ntp when config changed
  sudo: yes
  service:
    name={{ ntp_service }}
    state=restarted
  when: ntp_setup.changed
